<?xml version="1.0"?>
<!DOCTYPE softwarelist [
	<!ELEMENT softwarelist (software+)>
		<!ATTLIST softwarelist name CDATA #REQUIRED>
		<!ATTLIST softwarelist description CDATA #IMPLIED>
		<!ELEMENT software (description, year?, publisher, part*)>
			<!ATTLIST software name CDATA #REQUIRED>
			<!ATTLIST software cloneof CDATA #IMPLIED>
			<!ATTLIST software supported (yes|partial|no) "yes">
			<!ELEMENT description (#PCDATA)>
			<!ELEMENT year (#PCDATA)>
			<!ELEMENT publisher (#PCDATA)>
			<!ELEMENT part (dataarea*)>
				<!ATTLIST part name CDATA #REQUIRED>
				<!ATTLIST part interface CDATA #REQUIRED>
				<!-- feature is used to store things like pcb-type, mapper type, etc. Specific values depend on the system. -->
				<!ATTLIST part feature CDATA #IMPLIED>
				<!ELEMENT dataarea (rom*)>
					<!ATTLIST dataarea name CDATA #REQUIRED>
					<!ATTLIST dataarea size CDATA #REQUIRED>
					<!ATTLIST dataarea databits (8|16|32|64) "8">
					<!ATTLIST dataarea endian (big|little) "little">
					<!ELEMENT rom EMPTY>
						<!ATTLIST rom name CDATA #IMPLIED>
						<!ATTLIST rom size CDATA #REQUIRED>
						<!ATTLIST rom crc CDATA #IMPLIED>
						<!ATTLIST rom md5 CDATA #IMPLIED>
						<!ATTLIST rom sha1 CDATA #IMPLIED>
						<!ATTLIST rom offset CDATA #IMPLIED>
						<!ATTLIST rom status (baddump|nodump|good) "good">
						<!ATTLIST rom loadflag (load16_byte|load16_word|load16_word_swap|load32_byte|load32_word|load32_word_swap|load32_dword|load64_word|load64_word_swap|reload) #IMPLIED>
]>
<softwarelist name="pico" description="Sega Pico cartridges">
	<software name="101dalma">
		<description>101 Dalmatians (Prototype, 19960817-U)</description>
		<year>1996</year>
		<publisher>Sega</publisher>
		<part name="cart" interface="pico_cart">
			<dataarea name="rom" size="1048576">
				<rom name="101 dalmatians (prototype - aug 17, 1996 - u).bin" size="1048576" crc="602e237a" sha1="915d44cbc0d0f04be485609c1367a1d47f140942" offset="000000" />
			</dataarea>
		</part>
	</software>

	<software name="101dalma1" cloneof="101dalma">
		<description>101 Dalmatians (Prototype, 19960817-J)</description>
		<year>1996</year>
		<publisher>Sega</publisher>
		<part name="cart" interface="pico_cart">
			<dataarea name="rom" size="1048576">
				<rom name="101 dalmatians (prototype - aug 17, 1996 - j).bin" size="1048576" crc="cdc4dba2" sha1="ee1b794f03ee02124e22c4050f686f4f7b6e06df" offset="000000" />
			</dataarea>
		</part>
	</software>

	<software name="101dalma2" cloneof="101dalma">
		<description>101 Dalmatians (Prototype, 19960817-B)</description>
		<year>1996</year>
		<publisher>Sega</publisher>
		<part name="cart" interface="pico_cart">
			<dataarea name="rom" size="1048576">
				<rom name="101 dalmatians (prototype - aug 17, 1996 - b).bin" size="1048576" crc="d271f727" sha1="bbbb351396ae9c636092efc6780dd1f80f4ca854" offset="000000" />
			</dataarea>
		</part>
	</software>

	<software name="101dalma3" cloneof="101dalma">
		<description>101 Dalmatians (Prototype, 19960816)</description>
		<year>1996</year>
		<publisher>Sega</publisher>
		<part name="cart" interface="pico_cart">
			<dataarea name="rom" size="1048576">
				<rom name="101 dalmatians (prototype - aug 16, 1996).bin" size="1048576" crc="f0269662" sha1="7f7186de1a79427078a682aeca222e7df9994ffc" offset="000000" />
			</dataarea>
		</part>
	</software>

	<software name="101dalma4" cloneof="101dalma">
		<description>101 Dalmatians (Prototype, 19960814)</description>
		<year>1996</year>
		<publisher>Sega</publisher>
		<part name="cart" interface="pico_cart">
			<dataarea name="rom" size="1048576">
				<rom name="101 dalmatians (prototype - aug 14, 1996).bin" size="1048576" crc="16d9431c" sha1="e37c7b85b9c57301a9223507457ca0a78f7e4b24" offset="000000" />
			</dataarea>
		</part>
	</software>

	<software name="101dalma5" cloneof="101dalma">
		<description>101 Dalmatians (Prototype, 19960718)</description>
		<year>1996</year>
		<publisher>Sega</publisher>
		<part name="cart" interface="pico_cart">
			<dataarea name="rom" size="1048576">
				<rom name="101 dalmatians (prototype - jul 18, 1996).bin" size="1048576" crc="849abcb2" sha1="950888fd46a956c93baa3e938ee264b2de58055e" offset="000000" />
			</dataarea>
		</part>
	</software>

	<software name="101dalma6" cloneof="101dalma">
		<description>101 Dalmatians (Prototype, 19960705)</description>
		<year>1996</year>
		<publisher>Sega</publisher>
		<part name="cart" interface="pico_cart">
			<dataarea name="rom" size="1048576">
				<rom name="101 dalmatians (prototype - jul 05, 1996).bin" size="1048576" crc="3d17bfdc" sha1="8aef447eb11567ba3663d89ad417987a6d5b8cbf" offset="000000" />
			</dataarea>
		</part>
	</software>

	<software name="101dalma7" cloneof="101dalma">
		<description>101 Dalmatians (Prototype, 19960703)</description>
		<year>1996</year>
		<publisher>Sega</publisher>
		<part name="cart" interface="pico_cart">
			<dataarea name="rom" size="1048576">
				<rom name="101 dalmatians (prototype - jul 03, 1996).bin" size="1048576" crc="29d31f1e" sha1="7f8cfd2778876dd7ca03fa0a89a0da66bd7cf483" offset="000000" />
			</dataarea>
		</part>
	</software>

	<software name="101dalma8" cloneof="101dalma">
		<description>101 Dalmatians (Prototype, 19960531)</description>
		<year>1996</year>
		<publisher>Sega</publisher>
		<part name="cart" interface="pico_cart">
			<dataarea name="rom" size="1048576">
				<rom name="101 dalmatians (prototype - may 31, 1996).bin" size="1048576" crc="ea6fe243" sha1="15d9a25c6350640aae1a65b41d293bde436252d9" offset="000000" />
			</dataarea>
		</part>
	</software>

	<software name="101dalma9" cloneof="101dalma">
		<description>101 Dalmatians (Prototype, 19960521)</description>
		<year>1996</year>
		<publisher>Sega</publisher>
		<part name="cart" interface="pico_cart">
			<dataarea name="rom" size="1048576">
				<rom name="101 dalmatians (prototype - may 21, 1996).bin" size="1048576" crc="2c5eee07" sha1="1a909fb832d2b04d062f5c35f7ab1ed106573a5a" offset="000000" />
			</dataarea>
		</part>
	</software>

	<software name="101pikiw">
		<description>101 piki wan-chan (Jpn, Prototype, 19960817)</description>
		<year>1996</year>
		<publisher>Sega</publisher>
		<part name="cart" interface="pico_cart">
			<dataarea name="rom" size="1048576">
				<rom name="101 piki wan-chan rev 19960817 (1996)(appaloosa interactive - sega)(jp)(beta).bin" size="1048576" crc="cdc4dba2" sha1="ee1b794f03ee02124e22c4050f686f4f7b6e06df" offset="000000" />
			</dataarea>
		</part>
	</software>

	<software name="berenstb">
		<description>The Berenstain Bears' A School Day (Prototype, 19941220)</description>
		<year>1995</year>
		<publisher>Sega</publisher>
		<part name="cart" interface="pico_cart">
			<dataarea name="rom" size="1048576">
				<rom name="berenstain bears' a school day, the rev 19941220 (1995)(realtime associates - sega)(beta).bin" size="1048576" crc="2994dcee" sha1="6019bf5829925389b44414697e7329f8c2056437" offset="000000" />
			</dataarea>
		</part>
	</software>

	<software name="berenstb1" cloneof="berenstb">
		<description>The Berenstain Bears' A School Day (Prototype, 19950106)</description>
		<year>1995</year>
		<publisher>Sega</publisher>
		<part name="cart" interface="pico_cart">
			<dataarea name="rom" size="1048576">
				<rom name="berenstain bears' a school day, the rev 19950106 (1995)(realtime associates - sega)(beta).bin" size="1048576" crc="5dac3ecf" sha1="246e18fcbc271798f531944a6291ac6c9bb5840c" offset="000000" />
			</dataarea>
		</part>
	</software>

	<software name="berenstb2" cloneof="berenstb">
		<description>The Berenstain Bears' A School Day (Prototype, 19950113)</description>
		<year>1995</year>
		<publisher>Sega</publisher>
		<part name="cart" interface="pico_cart">
			<dataarea name="rom" size="1048564">
				<rom name="berenstain bears' a school day, the rev 19950113 (1995)(realtime associates - sega)(beta).bin" size="1048564" crc="291aa0bd" sha1="5677d64a2fd2ffa2baa1fd434f419407b5d47b5e" offset="000000" />
			</dataarea>
		</part>
	</software>

	<software name="berenstb3" cloneof="berenstb">
		<description>The Berenstain Bears' A School Day (Prototype, 19950116)</description>
		<year>1995</year>
		<publisher>Sega</publisher>
		<part name="cart" interface="pico_cart">
			<dataarea name="rom" size="1048564">
				<rom name="berenstain bears' a school day, the rev 19950116 (1995)(realtime associates - sega)(beta).bin" size="1048564" crc="56173be7" sha1="ccce25815ccff4468b42f8317025b5b66916645e" offset="000000" />
			</dataarea>
		</part>
	</software>

	<software name="berenstb4" cloneof="berenstb">
		<description>The Berenstain Bears' A School Day (Prototype, 19950126)</description>
		<year>1995</year>
		<publisher>Sega</publisher>
		<part name="cart" interface="pico_cart">
			<dataarea name="rom" size="1048564">
				<rom name="berenstain bears' a school day, the rev 19950126 (1995)(realtime associates - sega)(beta).bin" size="1048564" crc="098c3510" sha1="ab20a8063cd3650158a20572ae08048dc979a3e1" offset="000000" />
			</dataarea>
		</part>
	</software>

	<software name="berenstb5" cloneof="berenstb">
		<description>The Berenstain Bears' A School Day (Prototype, 19950127)</description>
		<year>1995</year>
		<publisher>Sega</publisher>
		<part name="cart" interface="pico_cart">
			<dataarea name="rom" size="1048564">
				<rom name="berenstain bears' a school day, the rev 19950127 (1995)(realtime associates - sega)(beta).bin" size="1048564" crc="4709d1cf" sha1="a6c0f0df6bb69aafcbdb49fd0ff5ef3ca7585cd9" offset="000000" />
			</dataarea>
		</part>
	</software>

	<software name="berenstb6" cloneof="berenstb">
		<description>The Berenstain Bears' A School Day (Prototype, 19950130)</description>
		<year>1995</year>
		<publisher>Sega</publisher>
		<part name="cart" interface="pico_cart">
			<dataarea name="rom" size="1048564">
				<rom name="berenstain bears' a school day, the rev 19950130 (1995)(realtime associates - sega)(beta).bin" size="1048564" crc="7b53784f" sha1="7128cea20f0695b69d552d5220097f4f4993ebef" offset="000000" />
			</dataarea>
		</part>
	</software>

	<software name="berenstb7" cloneof="berenstb">
		<description>The Berenstain Bears' A School Day (Prototype, 19950131)</description>
		<year>1995</year>
		<publisher>Sega</publisher>
		<part name="cart" interface="pico_cart">
			<dataarea name="rom" size="1048576">
				<rom name="berenstain bears' a school day, the rev 19950131 (1995)(realtime associates - sega)(beta).bin" size="1048576" crc="e92af9f1" sha1="f4ae09a8a0e11cd8bec95ec3ac3908ce6da7a30f" offset="000000" />
			</dataarea>
		</part>
	</software>

	<software name="crayon">
		<description>Crayon Shinchan Oekaki Note (Jpn, Prototype 1)</description>
		<year>1995</year>
		<publisher>Bandai</publisher>
		<part name="cart" interface="pico_cart">
			<dataarea name="rom" size="1048576">
				<rom name="crayon shinchan oekaki note (1995)(bandai)(jp)(beta).bin" size="1048576" crc="60656906" sha1="1e816a3f775b2bb5a5ae9b432ee026e65dad54d6" offset="000000" />
			</dataarea>
		</part>
	</software>

	<software name="crayona" cloneof="crayon">
		<description>Crayon Shinchan Oekaki Note (Jpn, Prototype 2)</description>
		<year>1995</year>
		<publisher>Bandai</publisher>
		<part name="cart" interface="pico_cart">
			<dataarea name="rom" size="524288">
				<rom name="crayon shinchan oekaki note (1995)(bandai)(jp)(beta)[a].bin" size="524288" crc="843c3af4" sha1="878733ffb5b0464f82f102f8500650bfe0b4add4" offset="000000" />
			</dataarea>
		</part>
	</software>

	<software name="crayonb" cloneof="crayon">
		<description>Crayon Shinchan Oekaki Note (Jpn, Prototype 3)</description>
		<year>1995</year>
		<publisher>Bandai</publisher>
		<part name="cart" interface="pico_cart">
			<dataarea name="rom" size="524288">
				<rom name="crayon shinchan oekaki note (1995)(bandai)(jp)(beta)[a2].bin" size="524288" crc="39d4c64b" sha1="52e115feb9d303993ca46aa36aa94a427f0ee141" offset="000000" />
			</dataarea>
		</part>
	</software>

	<software name="dolucky">
		<description>Dolucky no Oekaki House (Jpn, Prototype)</description>
		<year>1995</year>
		<publisher>&lt;unknown&gt;</publisher>
		<part name="cart" interface="pico_cart">
			<dataarea name="rom" size="524288">
				<rom name="dolucky no oekaki house (1995)(-)(jp)(beta).bin" size="524288" crc="4ce7b75d" sha1="aa906392c97cb12792a8cd026fdcb12d61490cf8" offset="000000" />
			</dataarea>
		</part>
	</software>

	<software name="gakkoben">
		<description>Gakken no Obenkyou Soft Tasizan Hikizan (Jpn, Prototype)</description>
		<year>1995</year>
		<publisher>Gakken</publisher>
		<part name="cart" interface="pico_cart">
			<dataarea name="rom" size="524288">
				<rom name="gakken no obenkyou soft tasizan hikizan (1995)(chips - gakken)(jp)(beta).bin" size="524288" crc="25639a73" sha1="d0a768236e21d05ea1734691ab9031ea7a4b3e47" offset="000000" />
			</dataarea>
		</part>
	</software>

	<software name="heiseiky">
		<description>Heisei Kyouiku Iinkai Jr. (Jpn, Prototype)</description>
		<year>1995</year>
		<publisher>&lt;unknown&gt;</publisher>
		<part name="cart" interface="pico_cart">
			<dataarea name="rom" size="524288">
				<rom name="heisei kyouiku iinkai jr. (1995)(-)(jp)(beta).bin" size="524288" crc="6e3e29b9" sha1="93c46585343e48e089ede74896f66b0006896c66" offset="000000" />
			</dataarea>
		</part>
	</software>

	<software name="heiseite">
		<description>Heisei Ten Sai Baka Bon Minna de Famiri-Restutoranni-Kun (Jpn, Prototype)</description>
		<year>1995</year>
		<publisher>&lt;unknown&gt;</publisher>
		<part name="cart" interface="pico_cart">
			<dataarea name="rom" size="524288">
				<rom name="heisei ten sai baka bon minna de famiri-restutoranni-kun (1995)(-)(jp)(beta).bin" size="524288" crc="3656af85" sha1="708cd58d6182a4f2448be3d2db97943c063a04f9" offset="000000" />
			</dataarea>
		</part>
	</software>

	<software name="hucklowl">
		<description>Huckle and Lowly's Busiest Day Ever (Prototype, 19941004)</description>
		<year>1994</year>
		<publisher>Sega</publisher>
		<part name="cart" interface="pico_cart">
			<dataarea name="rom" size="1048472">
				<rom name="huckle and lowly's busiest day ever rev 19941004 (1994)(realtime associates - sega)(beta).bin" size="1048472" crc="f0d08ce0" sha1="46213ef731dc66325e824b620e05577b1b4a9718" offset="000000" />
			</dataarea>
		</part>
	</software>

	<software name="hucklowla" cloneof="hucklowl">
		<description>Huckle and Lowly's Busiest Day Ever (Prototype, 19940919)</description>
		<year>1994</year>
		<publisher>Sega</publisher>
		<part name="cart" interface="pico_cart">
			<dataarea name="rom" size="1048472">
				<rom name="huckle and lowly's busiest day ever rev 19940919 (1994)(realtime associates - sega)(beta).bin" size="1048472" crc="74cadb40" sha1="7a87c09d5827df096ad8572da3a67a3913762589" offset="000000" />
			</dataarea>
		</part>
	</software>

	<software name="hucklowlb" cloneof="hucklowl">
		<description>Huckle and Lowly's Busiest Day Ever (Prototype, 19940721, F)</description>
		<year>1994</year>
		<publisher>Sega</publisher>
		<part name="cart" interface="pico_cart">
			<dataarea name="rom" size="1023740">
				<rom name="huckle and lowly's busiest day ever (prototype - jul 21, 1994) (f).bin" size="1023740" crc="026ca6f0" sha1="0e2898a56cf47576e68db772639c23a7efcaf026" offset="000000" />
			</dataarea>
		</part>
	</software>

	<software name="hucklowlc" cloneof="hucklowl">
		<description>Huckle and Lowly's Busiest Day Ever (Prototype, 19940510-D)</description>
		<year>1994</year>
		<publisher>Sega</publisher>
		<part name="cart" interface="pico_cart">
			<dataarea name="rom" size="1048576">
				<rom name="huckle and lowly's busiest day ever rev 19940510 (1994)(realtime associates - sega)(beta).bin" size="1048576" crc="42007e92" sha1="ce0b387427226baa4067d6eacebe90cef760a18e" offset="000000" />
			</dataarea>
		</part>
	</software>

	<software name="hucklowld" cloneof="hucklowl">
		<description>Huckle and Lowly's Busiest Day Ever (Prototype, 19940509-D)</description>
		<year>1994</year>
		<publisher>Sega</publisher>
		<part name="cart" interface="pico_cart">
			<dataarea name="rom" size="1048576">
				<rom name="huckle and lowly's busiest day ever rev 19940509 (1994)(realtime associates - sega)(beta)[a3].bin" size="1048576" crc="9a128886" sha1="c28b84f3ea1ada7accbc777683b55c3831c4ec9b" offset="000000" />
			</dataarea>
		</part>
	</software>

	<software name="hucklowle" cloneof="hucklowl">
		<description>Huckle and Lowly's Busiest Day Ever (Prototype, 19940509-C)</description>
		<year>1994</year>
		<publisher>Sega</publisher>
		<part name="cart" interface="pico_cart">
			<dataarea name="rom" size="1048576">
				<rom name="huckle and lowly's busiest day ever rev 19940509 (1994)(realtime associates - sega)(beta)[a2].bin" size="1048576" crc="bdd9c8fb" sha1="99223589cb5117cd8a82d780033545dcf0e53c8a" offset="000000" />
			</dataarea>
		</part>
	</software>

	<software name="hucklowlf" cloneof="hucklowl">
		<description>Huckle and Lowly's Busiest Day Ever (Prototype, 19940509-B)</description>
		<year>1994</year>
		<publisher>Sega</publisher>
		<part name="cart" interface="pico_cart">
			<dataarea name="rom" size="1048576">
				<rom name="huckle and lowly's busiest day ever rev 19940509 (1994)(realtime associates - sega)(beta)[a].bin" size="1048576" crc="782ea694" sha1="0f17bdd2747faf6a2c3bfe7846279b6ec02b8f60" offset="000000" />
			</dataarea>
		</part>
	</software>

	<software name="hucklowlg" cloneof="hucklowl">
		<description>Huckle and Lowly's Busiest Day Ever (Prototype, 19940509)</description>
		<year>1994</year>
		<publisher>Sega</publisher>
		<part name="cart" interface="pico_cart">
			<dataarea name="rom" size="1048576">
				<rom name="huckle and lowly's busiest day ever rev 19940509 (1994)(realtime associates - sega)(beta).bin" size="1048576" crc="a6bf6009" sha1="930cebb1af06fff37f0b03a1f5eb695f2581ffa5" offset="000000" />
			</dataarea>
		</part>
	</software>

	<software name="hucklowlh" cloneof="hucklowl">
		<description>Huckle and Lowly's Busiest Day Ever (Prototype, 19940506-B)</description>
		<year>1994</year>
		<publisher>Sega</publisher>
		<part name="cart" interface="pico_cart">
			<dataarea name="rom" size="1048576">
				<rom name="huckle and lowly's busiest day ever rev 19940506 (1994)(realtime associates - sega)(beta)[a].bin" size="1048576" crc="98840154" sha1="73df6e4fbf2f40efd73fa2268833c9a59e9398a1" offset="000000" />
			</dataarea>
		</part>
	</software>

	<software name="hucklowli" cloneof="hucklowl">
		<description>Huckle and Lowly's Busiest Day Ever (Prototype, 19940506-A)</description>
		<year>1994</year>
		<publisher>Sega</publisher>
		<part name="cart" interface="pico_cart">
			<dataarea name="rom" size="1048576">
				<rom name="huckle and lowly's busiest day ever rev 19940506 (1994)(realtime associates - sega)(beta).bin" size="1048576" crc="a271864c" sha1="8acead7e6af488b320d4abb7fce51d2fa0fd49b6" offset="000000" />
			</dataarea>
		</part>
	</software>

	<software name="hucklowlj" cloneof="hucklowl">
		<description>Huckle and Lowly's Busiest Day Ever (Prototype, 19940503-D)</description>
		<year>1994</year>
		<publisher>Sega</publisher>
		<part name="cart" interface="pico_cart">
			<dataarea name="rom" size="1048576">
				<rom name="huckle and lowly's busiest day ever rev 19940503 (1994)(realtime associates - sega)(beta)[a3].bin" size="1048576" crc="3491bda7" sha1="a8ba90e9f5071e7191c334ba1ce968fcef9d8ff8" offset="000000" />
			</dataarea>
		</part>
	</software>

	<software name="hucklowlk" cloneof="hucklowl">
		<description>Huckle and Lowly's Busiest Day Ever (Prototype, 19940503-C)</description>
		<year>1994</year>
		<publisher>Sega</publisher>
		<part name="cart" interface="pico_cart">
			<dataarea name="rom" size="1048576">
				<rom name="huckle and lowly's busiest day ever rev 19940503 (1994)(realtime associates - sega)(beta)[a2].bin" size="1048576" crc="828c773f" sha1="9c99abeac92bb7a536ea9c12c4f061ad13201261" offset="000000" />
			</dataarea>
		</part>
	</software>

	<software name="hucklowll" cloneof="hucklowl">
		<description>Huckle and Lowly's Busiest Day Ever (Prototype, 19940503-B)</description>
		<year>1994</year>
		<publisher>Sega</publisher>
		<part name="cart" interface="pico_cart">
			<dataarea name="rom" size="1048576">
				<rom name="huckle and lowly's busiest day ever rev 19940503 (1995)(realtime associates - sega)(beta).bin" size="1048576" crc="a79e8c5a" sha1="baf0ec378647144948db072d32f926f188bf69e7" offset="000000" />
			</dataarea>
		</part>
	</software>

	<software name="hucklowlm" cloneof="hucklowl">
		<description>Huckle and Lowly's Busiest Day Ever (Prototype, 19940503-A)</description>
		<year>1994</year>
		<publisher>Sega</publisher>
		<part name="cart" interface="pico_cart">
			<dataarea name="rom" size="1048576">
				<rom name="huckle and lowly's busiest day ever rev 19940503 (1994)(realtime associates - sega)(beta)[a].bin" size="1048576" crc="61b37530" sha1="10ce4256b5843c0323835a760f91d1f176e7db24" offset="000000" />
			</dataarea>
		</part>
	</software>

	<software name="hucklowln" cloneof="hucklowl">
		<description>Huckle and Lowly's Busiest Day Ever (Prototype, 19940427)</description>
		<year>1994</year>
		<publisher>Sega</publisher>
		<part name="cart" interface="pico_cart">
			<dataarea name="rom" size="1048576">
				<rom name="huckle and lowly's busiest day ever rev 19940427 (1994)(realtime associates - sega)(beta).bin" size="1048576" crc="11f32054" sha1="310683305721f63cd2a50db9464b5cf27fd877ad" offset="000000" />
			</dataarea>
		</part>
	</software>

	<software name="hucklowlo" cloneof="hucklowl">
		<description>Huckle and Lowly's Busiest Day Ever (Prototype, 19940426-E)</description>
		<year>1994</year>
		<publisher>Sega</publisher>
		<part name="cart" interface="pico_cart">
			<dataarea name="rom" size="1048576">
				<rom name="huckle and lowly's busiest day ever rev 19940426 (1994)(realtime associates - sega)(beta)[a2].bin" size="1048576" crc="fbc61621" sha1="c6392ccd79f1140739c42e476fd0c878a3680f75" offset="000000" />
			</dataarea>
		</part>
	</software>

	<software name="hucklowlp" cloneof="hucklowl">
		<description>Huckle and Lowly's Busiest Day Ever (Prototype, 19940426-D, Lower Half Broken)</description>
		<year>1994</year>
		<publisher>Sega</publisher>
		<part name="cart" interface="pico_cart">
			<dataarea name="rom" size="524288">
				<rom name="huckle and lowly's busiest day ever (prototype - apr 26, 1994 - d) (lower half broken).bin" size="524288" crc="5ea4c99c" sha1="86971ce70727fd3d8b52ba37fa9b7fe2d462037d" offset="000000" />
			</dataarea>
		</part>
	</software>

	<software name="hucklowlq" cloneof="hucklowl">
		<description>Huckle and Lowly's Busiest Day Ever (Prototype, 19940426-B)</description>
		<year>1994</year>
		<publisher>Sega</publisher>
		<part name="cart" interface="pico_cart">
			<dataarea name="rom" size="1048576">
				<rom name="huckle and lowly's busiest day ever rev 19940426 (1994)(realtime associates - sega)(beta)[a].bin" size="1048576" crc="f20535c5" sha1="f2dc08c8b0e4be40fec865e6530ffca7a474b6db" offset="000000" />
			</dataarea>
		</part>
	</software>

	<software name="hucklowlr" cloneof="hucklowl">
		<description>Huckle and Lowly's Busiest Day Ever (Prototype, 19940426-A)</description>
		<year>1994</year>
		<publisher>Sega</publisher>
		<part name="cart" interface="pico_cart">
			<dataarea name="rom" size="1048576">
				<rom name="huckle and lowly's busiest day ever rev 19940426 (1994)(realtime associates - sega)(beta).bin" size="1048576" crc="f325ab55" sha1="efaab9cb359acb46034b5e21ce8f5a4c2f8450e5" offset="000000" />
			</dataarea>
		</part>
	</software>

	<software name="hucklowls" cloneof="hucklowl">
		<description>Huckle and Lowly's Busiest Day Ever (Prototype, 19940424)</description>
		<year>1994</year>
		<publisher>Sega</publisher>
		<part name="cart" interface="pico_cart">
			<dataarea name="rom" size="1048472">
				<rom name="huckle and lowly's busiest day ever rev 19940424 (1994)(realtime associates - sega)(beta).bin" size="1048472" crc="4e032111" sha1="7e0966ef8dfd19102a8682f1d8f6ebd41a6903f0" offset="000000" />
			</dataarea>
		</part>
	</software>

	<software name="hucklowlt" cloneof="hucklowl">
		<description>Huckle and Lowly's Busiest Day Ever (Prototype, 19940422)</description>
		<year>1994</year>
		<publisher>Sega</publisher>
		<part name="cart" interface="pico_cart">
			<dataarea name="rom" size="1048576">
				<rom name="huckle and lowly's busiest day ever rev 19940422 (1994)(realtime associates - sega)(beta).bin" size="1048576" crc="2bfb25ac" sha1="227a2b1c36044ea4141d49eba006e927ecdd3337" offset="000000" />
			</dataarea>
		</part>
	</software>

	<software name="hucklowlu" cloneof="hucklowl">
		<description>Huckle and Lowly's Busiest Day Ever (Prototype, 19940302)</description>
		<year>1994</year>
		<publisher>Sega</publisher>
		<part name="cart" interface="pico_cart">
			<dataarea name="rom" size="667784">
				<rom name="huckle and lowly's busiest day ever rev 19940502 (1994)(realtime associates - sega)(beta).bin" size="667784" crc="265ad2d0" sha1="de457d6e1c6037a2c165c0f65037aadd9c73042c" offset="000000" />
			</dataarea>
		</part>
	</software>

	<software name="journee" cloneof="hucklowl">
		<description>La Journee La Plus Occupee de Huckle et Lowly (France, Prototype, 19940721)</description>
		<year>1994</year>
		<publisher>Sega</publisher>
		<part name="cart" interface="pico_cart">
			<dataarea name="rom" size="1023740">
				<rom name="journee la plus occupee de huckle et lowly, la rev 19940721 (1994)(realtime associates - sega)(fr)(beta).bin" size="1023740" crc="026ca6f0" sha1="0e2898a56cf47576e68db772639c23a7efcaf026" offset="000000" />
			</dataarea>
		</part>
	</software>

	<software name="kikansha">
		<description>Kikansha Thomas Ni Notte (Jpn, Prototype)</description>
		<year>1995</year>
		<publisher>Bandai</publisher>
		<part name="cart" interface="pico_cart">
			<dataarea name="rom" size="524288">
				<rom name="kikansha thomas ni notte (1995)(bandai)(jp)(beta).bin" size="524288" crc="32f926ac" sha1="cf7cce404c013c57bfb0e80c5da3213af64dd505" offset="000000" />
			</dataarea>
		</part>
	</software>

	<software name="lionking">
		<description>The Lion King - Adventures At Pride Rock (Prototype, 19950419)</description>
		<year>1995</year>
		<publisher>Sega</publisher>
		<part name="cart" interface="pico_cart">
			<dataarea name="rom" size="1048576">
				<rom name="lion king, the - adventures at pride rock rev 19950419 (1995)(realtime associates - sega)(beta).bin" size="1048576" crc="97effc7b" sha1="9df5d484be194516604b901349dee19fa30ee2f7" offset="000000" />
			</dataarea>
		</part>
	</software>

	<software name="lionking1" cloneof="lionking">
		<description>The Lion King - Adventures At Pride Rock (Prototype, 19950425)</description>
		<year>1995</year>
		<publisher>Sega</publisher>
		<part name="cart" interface="pico_cart">
			<dataarea name="rom" size="1048576">
				<rom name="lion king, the - adventures at pride rock rev 19950425 (1995)(realtime associates - sega)(beta).bin" size="1048576" crc="b948be65" sha1="0a7a95ef14997bc617b137e4e7da5cc3762bc516" offset="000000" />
			</dataarea>
		</part>
	</software>

	<software name="lionking2" cloneof="lionking">
		<description>The Lion King - Adventures At Pride Rock (Prototype, 19950501)</description>
		<year>1995</year>
		<publisher>Sega</publisher>
		<part name="cart" interface="pico_cart">
			<dataarea name="rom" size="1042622">
				<rom name="lion king, the - adventures at pride rock rev 19950501 (1995)(realtime associates - sega)(beta).bin" size="1042622" crc="d5ecd5fd" sha1="29f505bb944cec4b09e6a2baf7dd72427f9d1574" offset="000000" />
			</dataarea>
		</part>
	</software>

	<software name="lionking3" cloneof="lionking">
		<description>The Lion King - Adventures At Pride Rock (Prototype, 19950516)</description>
		<year>1995</year>
		<publisher>Sega</publisher>
		<part name="cart" interface="pico_cart">
			<dataarea name="rom" size="1036340">
				<rom name="lion king, the - adventures at pride rock rev 19950516 (1995)(realtime associates - sega)(beta).bin" size="1036340" crc="6fbfd61b" sha1="35b1ff9b842271055fea434406eb6d0d2dafcb0f" offset="000000" />
			</dataarea>
		</part>
	</software>

	<software name="lionking4" cloneof="lionking">
		<description>The Lion King - Adventures At Pride Rock (Prototype, 19950517)</description>
		<year>1995</year>
		<publisher>Sega</publisher>
		<part name="cart" interface="pico_cart">
			<dataarea name="rom" size="1036340">
				<rom name="lion king, the - adventures at pride rock rev 19950517 (1995)(realtime associates - sega)(beta).bin" size="1036340" crc="f943083f" sha1="fc2bb183b0aed8ad6134fd345d83d43fef924a27" offset="000000" />
			</dataarea>
		</part>
	</software>

	<software name="lionking5" cloneof="lionking">
		<description>The Lion King - Adventures At Pride Rock (Prototype, 19950522)</description>
		<year>1995</year>
		<publisher>Sega</publisher>
		<part name="cart" interface="pico_cart">
			<dataarea name="rom" size="1048576">
				<rom name="lion king, the - adventures at pride rock rev 19950522 (1995)(realtime associates - sega)(beta).bin" size="1048576" crc="3ad71894" sha1="92f6f45a4f635d42824fb6fb23b34854d47cf82d" offset="000000" />
			</dataarea>
		</part>
	</software>

	<software name="lionking6" cloneof="lionking">
		<description>The Lion King - Adventures At Pride Rock (Prototype, 19950615)</description>
		<year>1995</year>
		<publisher>Sega</publisher>
		<part name="cart" interface="pico_cart">
			<dataarea name="rom" size="1036340">
				<rom name="lion king, the - adventures at pride rock rev 19950615 (1995)(realtime associates - sega)(beta).bin" size="1036340" crc="0588d13c" sha1="0814754b867eb61f1e546910c4fd063960a85e62" offset="000000" />
			</dataarea>
		</part>
	</software>

	<software name="lionking7" cloneof="lionking">
		<description>The Lion King - Adventures At Pride Rock (Prototype, 19950616)</description>
		<year>1995</year>
		<publisher>Sega</publisher>