=== jsmess/jsmess/hash/softwarelist.dtd
<!ELEMENT softwarelist (software+)>
<!ATTLIST softwarelist name CDATA #REQUIRED>
<!ATTLIST softwarelist description CDATA #IMPLIED>
<!ELEMENT software (description, year?, publisher, part*)>
<!ATTLIST software name CDATA #REQUIRED>
<!ATTLIST software cloneof CDATA #IMPLIED>
<!ATTLIST software supported (yes|partial|no) "yes">
<!ELEMENT description (#PCDATA)>
<!ELEMENT year (#PCDATA)>
<!ELEMENT publisher (#PCDATA)>
<!ELEMENT part (feature*, dataarea*)>
<!ATTLIST part name CDATA #REQUIRED>
<!ATTLIST part interface CDATA #REQUIRED>
<!-- feature is used to store things like pcb-type, mapper type, etc. Specific values depend on the system. -->
<!ELEMENT feature EMPTY>
<!ATTLIST feature name CDATA #REQUIRED>
<!ATTLIST feature value CDATA #IMPLIED>
<!ELEMENT dataarea (rom*)>
<!ATTLIST dataarea name CDATA #REQUIRED>
<!ATTLIST dataarea size CDATA #REQUIRED>
<!ATTLIST dataarea databits (8|16|32|64) "8">
<!ATTLIST dataarea endian (big|little) "little">
<!ELEMENT rom EMPTY>
<!ATTLIST rom name CDATA #IMPLIED>
<!ATTLIST rom size CDATA #IMPLIED>
<!ATTLIST rom crc CDATA #IMPLIED>
<!ATTLIST rom md5 CDATA #IMPLIED>
<!ATTLIST rom sha1 CDATA #IMPLIED>
<!ATTLIST rom offset CDATA #IMPLIED>
<!ATTLIST rom value CDATA #IMPLIED>
<!ATTLIST rom status (baddump|nodump|good) "good">
<!ATTLIST rom loadflag (load16_byte|load16_word|load16_word_swap|load32_byte|load32_word|load32_word_swap|load32_dword|load64_word|load64_word_swap|reload|fill|continue) #IMPLIED>

=== jsmess/jsmess/hash/vidbrain.xml
<?xml version="1.0"?>
<!DOCTYPE softwarelist SYSTEM "softwarelist.dtd">
<!--

  Undumped cartridges:

  Expanders
  EXP 1   Expander 1
  EXP 2   Expander 2

  Money Management Series
  APL/S   The Computational Language
  VB-59   The Programmable
  VB-81   The Financier
  VB-1000 Money Manager
  VB-1100 Budget System
  VB-1200 Information Manager
  
  Communication Series
  CM01    Timeshare
  
  Education Series
  ED07    Musicianship 1
  ED08    Number Cross
  ED09    Historical Simulation - France in the Old Regime
  
  Entertainment Series
  EN07    Challenge Racer
  EN08    Music Programmer
  EN09    Programmable Football
  EN10    Computer Life
  
  Demonstration Series
  ST01    Demonstration

-->
<softwarelist name="vidbrain" description="VideoBrain Family Computer cartridges">

  <!-- Education Series -->
  
  <software name="musictch">
    <description>Music Teacher 1</description>
    <year>1978</year>
    <publisher>VideoBrain Computer Company</publisher>
    <!-- <serial>ED01</serial> -->
    <part name="cart" interface="vidbrain_cart">
      <dataarea name="rom" size="2048">
        <rom name="musicteacher1-ed01.bin" size="2048" crc="c8fee8cd" sha1="1a0a19ecedfb2d918e4e1a4eb604a07dc5e1113f" offset="0" />
      </dataarea>
    </part>
  </software>
  <software name="mathttr1">
    <description>Math Tutor 1</description>
    <year>1978</year>
    <publisher>VideoBrain Computer Company</publisher>
    <!-- <serial>ED02</serial> -->
    <part name="cart" interface="vidbrain_cart">
      <dataarea name="rom" size="4096">
        <rom name="mathtutor1-ed02.bin" size="4096" crc="db47f770" sha1="efe9e5f7ee95e157af892b84de5653c0f85a13b0" offset="0" />
      </dataarea>
    </part>
  </software>
  <software name="wrdwise1">
    <description>Wordwise 1</description>
    <year>1978</year>
    <publisher>VideoBrain Computer Company</publisher>
    <!-- <serial>ED03</serial> -->
    <part name="cart" interface="vidbrain_cart">
      <dataarea name="rom" size="2048">
        <rom name="wordwise1-ed03.bin" size="2048" crc="d1546212" sha1="91594485442e2dfad059e4ce42aa60b7a0519d91" offset="0" />
      </dataarea>
    </part>
  </software>
  <software name="wrdwise2">
    <description>Wordwise 2</description>
    <year>1978</year>
    <publisher>VideoBrain Computer Company</publisher>
    <!-- <serial>ED04</serial> -->
    <part name="cart" interface="vidbrain_cart">
      <dataarea name="rom" size="2048">
        <rom name="wordwise2-ed04.bin" size="2048" crc="4a08e999" sha1="0b17ead29aea643da84d495ebab5220e547abf99" offset="0" />
      </dataarea>
    </part>
  </software>
  <software name="vidartst">
    <description>VideoArtist</description>
    <year>1978</year>
    <publisher>VideoBrain Computer Company</publisher>
    <!-- <serial>ED05</serial> -->
    <part name="cart" interface="vidbrain_cart">
      <dataarea name="rom" size="2048">
        <rom name="videoartist-ed05.bin" size="2048" crc="d68795f8" sha1="dfb118d6bba837aa8e6b7feb19be7de40cd1e4fa" offset="0" />
      </dataarea>
    </part>
  </software>
  <software name="lemstand">
    <description>Lemonade Stand</description>
    <year>1978</year>
    <publisher>VideoBrain Computer Company</publisher>
    <!-- <serial>ED06</serial> -->
    <part name="cart" interface="vidbrain_cart">
      <dataarea name="rom" size="4096">
        <rom name="lemonadestand-ed06.bin" size="4096" crc="27c08d93" sha1="faf47261797692e9081dc24f957f8f38dc1a975d" offset="0" />
      </dataarea>
    </part>
  </software>

  <!-- Entertainment Series -->
  
  <software name="gladiatr">
    <description>Gladiator</description>
    <year>1978</year>
    <publisher>VideoBrain Computer Company</publisher>
    <!-- <serial>EN01</serial> -->
    <part name="cart" interface="vidbrain_cart">
      <dataarea name="rom" size="4096">
        <rom name="gladiator-en01.bin" size="4096" crc="e6a88a49" sha1="ffdb06a714cc5bafa980db0742d0364ee5658c05" offset="0" />
      </dataarea>
    </part>
  </software>
  <software name="pinball">
    <description>Pinball</description>
    <year>1978</year>
    <publisher>VideoBrain Computer Company</publisher>
    <!-- <serial>EN02</serial> -->
    <part name="cart" interface="vidbrain_cart">
      <dataarea name="rom" size="2048">
        <rom name="pinball-en02.bin" size="2048" crc="484331ff" sha1="0bd04368692a55bf89f8ec7ff1a29cff3a398b9f" offset="0" />
      </dataarea>
    </part>
  </software>
  <software name="tennis">
    <description>Tennis</description>
    <year>1978</year>
    <publisher>VideoBrain Computer Company</publisher>
    <!-- <serial>EN03</serial> -->
    <part name="cart" interface="vidbrain_cart">
      <dataarea name="rom" size="4096">
        <rom name="tennis-en03.bin" size="4096" crc="1942f852" sha1="74e8304d8ad0328655627e21c0305b72c11a5dda" offset="0" />
      </dataarea>
    </part>
  </software>
  <software name="checkers">
    <description>Checkers</description>
    <year>1978</year>
    <publisher>VideoBrain Computer Company</publisher>
    <!-- <serial>EN04</serial> -->
    <part name="cart" interface="vidbrain_cart">
      <dataarea name="rom" size="4096">
        <rom name="checkers-en04.bin" size="4096" crc="24c53410" sha1="f12f448d1f62b56318cb94b8f802180d561e3ee5" offset="0" />
      </dataarea>
    </part>
  </software>
  <software name="blakjack">
    <description>Blackjack</description>
    <year>1978</year>
    <publisher>VideoBrain Computer Company</publisher>
    <!-- <serial>EN05</serial> -->
    <part name="cart" interface="vidbrain_cart">
      <dataarea name="rom" size="2048">
        <rom name="blackjack-en05.bin" size="2048" crc="47f02b92" sha1="23fd10c9674d304f2a0a4ae37e3afb6a25906b1c" offset="0" />
      </dataarea>
    </part>
  </software>
  <software name="vicevers">
    <description>Vice Versa</description>
    <year>1978</year>
    <publisher>VideoBrain Computer Company</publisher>
    <!-- <serial>EN06</serial> -->
    <part name="cart" interface="vidbrain_cart">
      <dataarea name="rom" size="4096">
        <rom name="viceversa-en06.bin" size="4096" crc="e23504ee" sha1="c5b4b62c9e0db998c2c4df6f71713a1df35c8bf4" offset="0" />
      </dataarea>
    </part>
  </software>
</softwarelist>

=== jsmess/jsmess/hash/c128_cart.xml
<?xml version="1.0"?>
<!DOCTYPE softwarelist SYSTEM "softwarelist.dtd">
<softwarelist name="c128_cart" description="Commodore 128 cartridges">
	
	<software name="c128diag" supported="no">
		<description>C128 Diagnostic v1.1</description>
		<year>1987</year>
		<publisher>Commodore</publisher>
		<part name="cart" interface="c128_cart">
			<feature name="game" value="1" />
			<feature name="exrom" value="1" />

			<dataarea name="roml" size="0x2000">
				<rom name="c128diag.bin" size="0x2000" crc="584f6750" sha1="b3cfd8508b887e9c7e72ed2b0c44fe63e6b44ac4" offset="0x0000" />
			</dataarea>
		</part>
	</software>
	
	<software name="warpspd" supported="no">
		<description>C128 Warp Speed v1</description>
		<year>1987</year>
		<publisher>Cinemaware</publisher>
		<part name="cart" interface="c128_cart">
			<feature name="cart_type" value="warp_speed" />
			<feature name="game" value="1" />
			<feature name="exrom" value="1" />

			<dataarea name="roml" size="0x4000">
				<!--
				data = BITSWAP8(7,6,5,2,0,1,3,4)
				address = BITSWAP14(12,13,5,2,7,9,11,10,8,6,4,3,1,0)
				-->
				<rom name="c128warpspeedv1-1987.bin" size="0x4000" crc="986f61b8" sha1="31d7b7f864904deb947db3658d7da691b4db4fc2" offset="0x0000" />
			</dataarea>
		</part>
	</software>
	
	<software name="warpspd2" cloneof="warpspd" supported="no">
		<description>C128 Warp Speed v2</description>
		<year>1987</year>
		<publisher>Cinemaware</publisher>
		<part name="cart" interface="c128_cart">
			<feature name="cart_type" value="warp_speed" />
			<feature name="game" value="1" />
			<feature name="exrom" value="1" />

			<dataarea name="roml" size="0x4000">
				<!--
				data = BITSWAP8(7,6,5,2,0,1,3,4)
				address = BITSWAP14(12,13,5,2,7,9,11,10,8,6,4,3,1,0)
				-->
				<rom name="c128warpspeedv2-1987.bin" size="0x4000" crc="c5dd7720" sha1="062ea091bf085b09ce8ea85a9a498734b9138906" offset="0x0000" />
			</dataarea>
		</part>
	</software>
	
	<software name="mach128" supported="no">
		<description>MACH 128 v.1A</description>
		<year>1985</year>
		<publisher>Access Software</publisher>
		<part name="cart" interface="c128_cart">
			<feature name="cart_type" value="mach128" />
			<feature name="game" value="1" />
			<feature name="exrom" value="1" />

			<dataarea name="roml" size="0x2000">
				<rom name="mach_128_v1a.bin" size="0x2000" crc="f91ed380" sha1="6f04d73fcde8b28903075e3adcd2d7ff49d2518a" offset="0x0000" />
			</dataarea>
		</part>
		<part name="flop" interface="floppy_5_25">
			<dataarea name="flop" size="174848">
				<rom name="mach_128_utilities.d64" size="174848" crc="5fb309f5" sha1="2f5e6c5c028654500425be7a703ba5d9bf72bdab" offset="0" />
			</dataarea>
		</part>
	</software>
	
	<software name="mach128_2a" cloneof="mach128" supported="no">
		<description>MACH 128 v.2A</description>
		<year>1985</year>
		<publisher>Access Software</publisher>
		<part name="cart" interface="c128_cart">
			<feature name="cart_type" value="mach128" />
			<feature name="game" value="1" />
			<feature name="exrom" value="1" />

			<dataarea name="roml" size="0x2000">
				<rom name="mach_128_v2a.bin" size="0x2000" crc="fc60d92e" sha1="7f487134d314b4c5158954ad057e01c0da32a468" offset="0x0000" />
			</dataarea>
		</part>
		<part name="flop" interface="floppy_5_25">
			<dataarea name="flop" size="174848">
				<rom name="mach_128_utilities.d64" size="174848" crc="5fb309f5" sha1="2f5e6c5c028654500425be7a703ba5d9bf72bdab" offset="0" />
			</dataarea>
		</part>
	</software>

</softwarelist>

=== jsmess/jsmess/hash/apple1.xml
<?xml version="1.0"?>
<!DOCTYPE softwarelist SYSTEM "softwarelist.dtd">

<softwarelist name="apple1" description="Apple 1 tape images">

	<software name="basic">
		<description>Apple I Basic</description>
		<year>19??</year>
		<publisher>&lt;unknown&gt;</publisher>
		<info name="usage" value="Load at E000.EFFFR, enter at E000R" />
		<part name="cass" interface="apple1_cass">
			<dataarea name="cass" size="6644780">
				<rom name="apple1basic.wav" size="6644780" crc="cd5cf5a4" sha1="ef58e776683581ea6af869ee7775fc0d3ad577b9" offset="0" />
			</dataarea>
		</part>
	</software>

<!-- This version does seem to work better than the above, so we include it temporarily until we fix the subtle bug causing the parent not to be loaded properly -->
	<software name="basica" cloneof="basic">
		<description>Apple I Basic (Alt)</description>
		<year>19??</year>
		<publisher>&lt;unknown&gt;</publisher>
		<info name="usage" value="Load at E000.EFFFR, enter at E000R" />
		<part name="cass" interface="apple1_cass">
			<dataarea name="cass" size="3663918">
				<rom name="apple1bas.wav" size="3663918" crc="1914635e" sha1="e5f112bec9236d42c3b5618df0d4607053b0078f" offset="0" />
			</dataarea>
		</part>
	</software>

	<software name="llander">
		<description>Lunar Lander</description>
		<year>19??</year>
		<publisher>&lt;unknown&gt;</publisher>
		<info name="usage" value="Load at 300.0A00R, enter at 0300R" />
		<part name="cass" interface="apple1_cass">
			<dataarea name="cass" size="3350056">
				<rom name="lunar lander.wav" size="3350056" crc="3c87f6cd" sha1="de99cf33433e9b53b74920f3be258a4ce295ca2d" offset="0" />
			</dataarea>
		</part>
	</software>

	<software name="mastmind">
		<description>Mastermind</description>
		<year>19??</year>
		<publisher>&lt;unknown&gt;</publisher>
		<info name="usage" value="Load at 300.03FFR, enter at 0300R" />
		<part name="cass" interface="apple1_cass">
			<dataarea name="cass" size="1196032">
				<rom name="mastermind.wav" size="1196032" crc="b44936a4" sha1="8acb9ee5fe7ee100620c2de5c95d50a7c69c881a" offset="0" />
			</dataarea>
		</part>
	</software>

	<software name="microchs">
		<description>Microchess</description>
		<year>19??</year>
		<publisher>&lt;unknown&gt;</publisher>
		<info name="usage" value="Load at 1000.18FFR, enter at 1000R" />
		<part name="cass" interface="apple1_cass">
			<dataarea name="cass" size="4052152">
				<rom name="microchess.wav" size="4052152" crc="9b3ca487" sha1="2317cc4a7609ebaaf2ef9e23b5f11eda4d1fbf29" offset="0" />
			</dataarea>
		</part>
	</software>

<!-- Other games require BASIC to be loaded first -->

	<software name="aceyduc">
		<description>AceyDucey</description>
		<year>19??</year>
		<publisher>&lt;unknown&gt;</publisher>
		<info name="usage" value="First load BASIC, then load at 4A.00FFR800.FFFR, enter at E2B3R" />
		<part name="cass" interface="apple1_cass">
			<dataarea name="cass" size="5736772">
				<rom name="aceyducey.wav" size="5736772" crc="793422b8" sha1="4e9c5610164efbae963e8b5988ff62f41a053020" offset="0" />
			</dataarea>
		</part>
	</software>

	<software name="alicetel">
		<description>Apple I Enhanced Checkers</description>
		<year>19??</year>
		<publisher>&lt;unknown&gt;</publisher>
		<info name="usage" value="First load BASIC, then load at 4A.00FFR300.FFFR, enter at E2B3R" />
		<part name="cass" interface="apple1_cass">
			<dataarea name="cass" size="9179180">
				<rom name="applei enhanced checkers.wav" size="9179180" crc="faed6233" sha1="a86f20520642ee9d3a174d6aad1a08080830284e" offset="0" />
			</dataarea>
		</part>
	</software>

	<software name="blckjack">
		<description>Blackjack</description>
		<year>19??</year>
		<publisher>&lt;unknown&gt;</publisher>
		<info name="usage" value="First load BASIC, then load at 4A.00FFR800.FFFR, enter at E2B3R" />
		<part name="cass" interface="apple1_cass">
			<dataarea name="cass" size="5723176">
				<rom name="blackjack.wav" size="5723176" crc="9486b37b" sha1="9de34b03c06a75f59bd5295ecc1a3c69858d61b9" offset="0" />
			</dataarea>
		</part>
	</software>

	<software name="bowling">
		<description>Bowling</description>
		<year>19??</year>
		<publisher>&lt;unknown&gt;</publisher>
		<info name="usage" value="First load BASIC, then load at 4A.00FFR300.FFFR, enter at E2B3R" />
		<part name="cass" interface="apple1_cass">
			<dataarea name="cass" size="6837948">
				<rom name="bowling.wav" size="6837948" crc="22383368" sha1="ef33153f66dc37f238c3fe646106742cdc86fa23" offset="0" />
			</dataarea>
		</part>
	</software>

	<software name="buzzword">
		<description>Buzzword</description>
		<year>19??</year>
		<publisher>&lt;unknown&gt;</publisher>
		<info name="usage" value="First load BASIC, then load at 4A.00FFR300.FFFR, enter at E2B3R" />
		<part name="cass" interface="apple1_cass">
			<dataarea name="cass" size="6824368">
				<rom name="buzzword.wav" size="6824368" crc="2c040f8e" sha1="5811e662672be7f3a0b757ec129e896c53da6d6d" offset="0" />
			</dataarea>
		</part>
	</software>

	<software name="craps">
		<description>Craps</description>
		<year>19??</year>
		<publisher>&lt;unknown&gt;</publisher>
		<info name="usage" value="First load BASIC, then load at 4A.00FFR300.FFFR, enter at E2B3R" />
		<part name="cass" interface="apple1_cass">
			<dataarea name="cass" size="6867496">
				<rom name="craps.wav" size="6867496" crc="d9675f54" sha1="f7d7f4b3672316b9b1a5bfb20e6209ffb65b8c3f" offset="0" />
			</dataarea>
		</part>
	</software>

	<software name="dealnod">
		<description>Deal or No Deal</description>
		<year>19??</year>
		<publisher>&lt;unknown&gt;</publisher>
		<info name="usage" value="First load BASIC, then load at 4A.00FFR300.FFFR, enter at E2B3R" />
		<part name="cass" interface="apple1_cass">
			<dataarea name="cass" size="18392504">
				<rom name="deal or no deal.wav" size="18392504" crc="28ad3585" sha1="bf59a22794a755c711b429f6633135402cd12e36" offset="0" />
			</dataarea>
		</part>
	</software>

	<software name="hamurabi">
		<description>Hamurabi</description>
		<year>19??</year>
		<publisher>&lt;unknown&gt;</publisher>
		<info name="usage" value="First load BASIC, then load at 4A.00FFR300.FFFR, enter at E2B3R" />
		<part name="cass" interface="apple1_cass">
			<dataarea name="cass" size="6953140">
				<rom name="hamurabi.wav" size="6953140" crc="9760bd93" sha1="294b57fc0970ce0844dc615ff017ead11b1ebba1" offset="0" />
			</dataarea>
		</part>
	</software>

	<software name="hilo">
		<description>HiLo</description>
		<year>19??</year>
		<publisher>&lt;unknown&gt;</publisher>
		<info name="usage" value="First load BASIC, then load at 4A.00FFR800.FFFR, enter at E2B3R" />
		<part name="cass" interface="apple1_cass">
			<dataarea name="cass" size="3067904">
				<rom name="hilo.wav" size="3067904" crc="21024b5d" sha1="acc525e0a5cea33d1c4e77673045e94e2608c1ba" offset="0" />
			</dataarea>
		</part>
	</software>

	<software name="slots">
		<description>Slots</description>
		<year>19??</year>
		<publisher>&lt;unknown&gt;</publisher>
		<info name="usage" value="First load BASIC, then load at 4A.00FFR300.FFFR, enter at E2B3R" />
		<part name="cass" interface="apple1_cass">
			<dataarea name="cass" size="6929500">
				<rom name="slots.wav" size="6929500" crc="dd90caea" sha1="5b69702d45d7288f4d8b3e74fe39ed74235ad122" offset="0" />
			</dataarea>
		</part>
	</software>

	<software name="startrek">
		<description>Star Trek</description>
		<year>19??</year>
		<publisher>&lt;unknown&gt;</publisher>
		<info name="usage" value="First load BASIC, then load at 4A.00FFR300.FFFR, enter at E2B3R" />
		<part name="cass" interface="apple1_cass">
			<dataarea name="cass" size="11126828">
				<rom name="startrek.wav" size="11126828" crc="42d7ff61" sha1="508d585d824e75f6ef77a818e238948187e3dc73" offset="0" />
			</dataarea>
		</part>
	</software>

	<software name="start2k3">
		<description>Star Trek 2003</description>
		<year>19??</year>
		<publisher>&lt;homebrew&gt;</publisher>
		<info name="usage" value="First load BASIC, then load at 4A.00FFR300.FFFR, enter at E2B3R" />
		<part name="cass" interface="apple1_cass">
			<dataarea name="cass" size="18338436">
				<rom name="startrek2003.wav" size="18338436" crc="659d91a9" sha1="7754c0883a342f68023ebed198b27359dc602f56" offset="0" />
			</dataarea>
		</part>
	</software>

	<software name="wordx">
		<description>WordCross</description>
		<year>19??</year>
		<publisher>&lt;unknown&gt;</publisher>
		<info name="usage" value="First load BASIC, then load at 4A.00FFR300.FFFR, enter at E2B3R" />
		<part name="cass" interface="apple1_cass">
			<dataarea name="cass" size="7294204">
				<rom name="wordcross.wav" size="7294204" crc="1330687d" sha1="433587c369cc82dbc6ac6d4a35a36f9225df63aa" offset="0" />
			</dataarea>
		</part>
	</software>

	<software name="wumpus">
		<description>Wumpus</description>
		<year>19??</year>
		<publisher>&lt;unknown&gt;</publisher>
		<info name="usage" value="First load BASIC, then load at 4A.00FFR300.FFFR, enter at E2B3R" />
		<part name="cass" interface="apple1_cass">
			<dataarea name="cass" size="3729408">
				<rom name="wumpus.wav" size="3729408" crc="83cb19a5" sha1="cb3c98b1963a2688ccc8315d0f8866bf572743b9" offset="0" />
			</dataarea>
		</part>
	</software>

</softwarelist>

=== jsmess/jsmess/hash/pc8201.xml
<?xml version="1.0"?>
<!DOCTYPE softwarelist SYSTEM "softwarelist.dtd">

<softwarelist name="pc8201_cart" description="NEC PC-8201 Option ROM">
  <software name="r2c">
    <description>ROM2/Cleuseau</description>
    <year>198?</year>
    <publisher>Polar Engineering</publisher>

    <part name="cart" interface="pc8201_cart">
      <dataarea name="rom" size="0x8000">
        <rom name="r2cnec.bin" size="0x8000" crc="66A30B04" sha1="8E9AACCF70F73DEE1D86060D11587B80437866E1" offset="0x0000" />
      </dataarea>
    </part>
  </software>

  <software name="tword">
    <description>T-Word with Sardine v1.33</description>
    <year>1986</year>
    <publisher>Traveling Software</publisher>

    <part name="cart" interface="pc8201_cart">
      <dataarea name="rom" size="0x8000">
        <rom name="sardnec.bin" size="0x8000" crc="cca9fac7" sha1="8e99f3fe916c011243a28769785e99ab9eecc261" offset="0x0000" />
      </dataarea>
    </part>
  </software>

  <software name="tsdos">
    <description>TS-DOS v4.00</description>
    <year>1987</year>
    <publisher>Traveling Software</publisher>

    <part name="cart" interface="pc8201_cart">
      <dataarea name="rom" size="0x8000">
        <rom name="tsdosnec.bin" size="0x8000" crc="5aa603c9" sha1="bc0d334517008c5b22b71686badf9e689f77a5a8" offset="0x0000" />
      </dataarea>
    </part>
  </software>

  <software name="ur2">
    <description>The Ultimate ROM II v2.11</description>
    <year>1986</year>
    <publisher>Traveling Software</publisher>

    <part name="cart" interface="pc8201_cart">
      <dataarea name="rom" size="0x8000">
        <rom name="ur2nec.bin" size="0x8000" crc="cf4335e2" sha1="1304d8661783e90ebf8631d572127b7cd1b073d3" offset="0x0000" />
      </dataarea>
    </part>
  </software>
</softwarelist>

=== jsmess/jsmess/hash/sgx.xml
<?xml version="1.0"?>
<!DOCTYPE softwarelist SYSTEM "softwarelist.dtd">
<softwarelist name="sgx" description="NEC Supergrafx cartridges">
	<software name="1941">
		<!-- Release Date: 1991-08-23 -->
		<description>1941 - Counter Attack</description>
		<year>1991</year>
		<publisher>Hudson</publisher>
		<part name="cart" interface="pce_cart">
			<dataarea name="rom" size="1048576">
				<rom name="1941 - counter attack (japan).pce" size="1048576" crc="8c4588e2" sha1="66873b0e0cc699aa75daf06a3f74c0508037e605" offset="000000" />
			</dataarea>
		</part>
	</software>

	<software name="aldynes">
		<!-- Release Date: 1991-02-22 -->
		<description>Aldynes</description>
		<year>1991</year>
		<publisher>Hudson</publisher>
		<part name="cart" interface="pce_cart">
			<dataarea name="rom" size="1048576">
				<rom name="aldynes (japan).pce" size="1048576" crc="4c2126b0" sha1="d876248ee1b80ad11633fd4be8aa21a187b52193" offset="000000" />
			</dataarea>
		</part>
	</software>

	<software name="battlace">
		<!-- Release Date: 1989-11-30 -->
		<description>Battle Ace</description>
		<year>1989</year>
		<publisher>Hudson</publisher>
		<part name="cart" interface="pce_cart">
			<dataarea name="rom" size="524288">
				<rom name="battle ace (japan).pce" size="524288" crc="3b13af61" sha1="edc8f7d2233c92ebd309ac804527c461851a4b63" offset="000000" />
			</dataarea>
		</part>
	</software>

	<software name="daimakai">
		<!-- Release Date: 1990-07-27 -->
		<description>Daimakai Mura</description>
		<year>1990</year>
		<publisher>NEC Avenue</publisher>
		<part name="cart" interface="pce_cart">
			<dataarea name="rom" size="1048576">
				<rom name="daimakai mura (japan).pce" size="1048576" crc="b486a8ed" sha1="cab9e4a1a8b6da07cc2c5cc35949928199a417ee" offset="000000" />
			</dataarea>
		</part>
	</software>

	<software name="granzort">
		<!-- Release Date: 1990-04-06 -->
		<description>Madou Ou Granzort</description>
		<year>1990</year>
		<publisher>Hudson</publisher>
		<part name="cart" interface="pce_cart">
			<dataarea name="rom" size="524288">
				<rom name="madou ou granzort (japan).pce" size="524288" crc="1f041166" sha1="5ed16565753c902e14da9a0c5361ef01fa74463b" offset="000000" />
			</dataarea>
		</part>
	</software>

</softwarelist>
