=== jsmess/jsmess/hash/softwarelist.dtd
<!ELEMENT softwarelist (software+)>
<!ATTLIST softwarelist name CDATA #REQUIRED>
<!ATTLIST softwarelist description CDATA #IMPLIED>
<!ELEMENT software (description, year?, publisher, part*)>
<!ATTLIST software name CDATA #REQUIRED>
<!ATTLIST software cloneof CDATA #IMPLIED>
<!ATTLIST software supported (yes|partial|no) "yes">
<!ELEMENT description (#PCDATA)>
<!ELEMENT year (#PCDATA)>
<!ELEMENT publisher (#PCDATA)>
<!ELEMENT part (feature*, dataarea*)>
<!ATTLIST part name CDATA #REQUIRED>
<!ATTLIST part interface CDATA #REQUIRED>
<!-- feature is used to store things like pcb-type, mapper type, etc. Specific values depend on the system. -->
<!ELEMENT feature EMPTY>
<!ATTLIST feature name CDATA #REQUIRED>
<!ATTLIST feature value CDATA #IMPLIED>
<!ELEMENT dataarea (rom*)>
<!ATTLIST dataarea name CDATA #REQUIRED>
<!ATTLIST dataarea size CDATA #REQUIRED>
<!ATTLIST dataarea databits (8|16|32|64) "8">
<!ATTLIST dataarea endian (big|little) "little">
<!ELEMENT rom EMPTY>
<!ATTLIST rom name CDATA #IMPLIED>
<!ATTLIST rom size CDATA #IMPLIED>
<!ATTLIST rom crc CDATA #IMPLIED>
<!ATTLIST rom md5 CDATA #IMPLIED>
<!ATTLIST rom sha1 CDATA #IMPLIED>
<!ATTLIST rom offset CDATA #IMPLIED>
<!ATTLIST rom value CDATA #IMPLIED>
<!ATTLIST rom status (baddump|nodump|good) "good">
<!ATTLIST rom loadflag (load16_byte|load16_word|load16_word_swap|load32_byte|load32_word|load32_word_swap|load32_dword|load64_word|load64_word_swap|reload|fill|continue) #IMPLIED>

=== jsmess/jsmess/hash/juicebox.xml
<?xml version="1.0"?>
<!DOCTYPE softwarelist SYSTEM "softwarelist.dtd">
<softwarelist name="juicebox" description="Mattel Juice Box SmartMedia Flash ROM">
	<software name="kidsnedo">
		<description>Codename: Kids Next Door</description>
		<year>2003</year>
		<publisher>Cartoon Network</publisher>
		<part name="memc" interface="smartmedia">
			<dataarea name="rom" size="34604032">
				<rom name="kidsnedo.smc" size="34604032" crc="e917e1f2" sha1="42c56a8b9a2ae076956b98e8bd71e1dfd841d002" offset="0x00000" />
			</dataarea>
		</part>
	</software>
	<software name="yugioh">
		<description>Yu-Gi-Oh!</description>
		<year>1996</year>
		<publisher>Kazuki Takahashi</publisher>
		<part name="memc" interface="smartmedia">
			<dataarea name="rom" size="34604032">
				<rom name="yugioh.smc" size="34604032" crc="0a97c7d6" sha1="1b2375c9ef1bbd5cae0c3f0ac20511a36523e86a" offset="0x00000"/>
			</dataarea>
		</part>
	</software>
</softwarelist>

=== jsmess/jsmess/hash/pc8001_flop.xml
<?xml version="1.0"?>
<!DOCTYPE softwarelist SYSTEM "softwarelist.dtd">
<softwarelist name="pc8001_flop" description="NEC PC-8001 &amp; PC-8001SR disk images">

<!-- DISKS -->

	<software name="crmanor">
		<description>Cranston Manor</description>
		<year>19??</year>
		<publisher>&lt;unknown&gt;</publisher>
		<part name="flop1" interface="pc8001_flop">
			<dataarea name="flop" size="693344">
				<rom name="cranston_manor_v80.d88" size="693344" crc="54e4e5e7" sha1="4a1a3aa26a71bf61e0fb81a9a53c438cbd2745b5" offset="0" />
			</dataarea>
		</part>
	</software>

	<software name="ulysses">
		<description>Ulysses</description>
		<year>19??</year>
		<publisher>&lt;unknown&gt;</publisher>
		<part name="flop1" interface="pc8001_flop">
			<dataarea name="flop" size="1042192">
				<rom name="ulysses_v80.d88" size="1042192" crc="b4ee359c" sha1="4cb6a4a69b942184d43e639ec7ae9c20c1c5c20c" offset="0" />
			</dataarea>
		</part>
	</software>

	<software name="zaxus">
		<description>Zaxus</description>
		<year>19??</year>
		<publisher>&lt;unknown&gt;</publisher>
		<part name="flop1" interface="pc8001_flop">
			<dataarea name="flop" size="40128">
				<rom name="zaxus.d88" size="40128" crc="a5fed0de" sha1="8d7a2df8eb5b0934c6abad75af962c6a979d121d" offset="0" />
			</dataarea>
		</part>
	</software>

<!-- SR DISKS -->

	<software name="laptick">
		<description>Laptick</description>
		<year>19??</year>
		<publisher>&lt;unknown&gt;</publisher>
		<part name="flop1" interface="pc8001_flop">
			<dataarea name="flop" size="348720">
				<rom name="laptick_v80.d88" size="348720" crc="ad4d2567" sha1="9ff209c3e0aff4afc71ebe73740a5a97b2428394" offset="0" />
			</dataarea>
		</part>
	</software>

	<software name="mappy">
		<description>Mappy</description>
		<year>19??</year>
		<publisher>&lt;unknown&gt;</publisher>
		<part name="flop1" interface="pc8001_flop">
			<dataarea name="flop" size="353200">
				<rom name="mappy_v80.d88" size="353200" crc="a9978924" sha1="0bf806b8f1ef54960d855c62af367dd2e1ff2351" offset="0" />
			</dataarea>
		</part>
	</software>

	<software name="shitokei">
		<description>Shitokei...</description>
		<year>19??</year>
		<publisher>&lt;unknown&gt;</publisher>
		<part name="flop1" interface="pc8001_flop">
			<dataarea name="flop" size="348848">
				<rom name="shikotei_v80.d88" size="348848" crc="23f27524" sha1="6b0629a526f11df8c889eeef5d74e518d00b9354" offset="0" />
			</dataarea>
		</part>
	</software>

	<software name="xanadu">
		<description>Xanadu</description>
		<year>19??</year>
		<publisher>&lt;unknown&gt;</publisher>
		<part name="flop1" interface="pc8001_flop">
			<dataarea name="flop" size="834800">
				<rom name="xanadu_v80.d88" size="834800" crc="534e44cf" sha1="d79f694897801150e131e58e02622ec43ebca4ec" offset="0" />
			</dataarea>
		</part>
	</software>

	<software name="n80basic">
		<description>N80 BASIC</description>
		<year>19??</year>
		<publisher>&lt;unknown&gt;</publisher>
		<part name="flop1" interface="pc8001_flop">
			<dataarea name="flop" size="348848">
				<rom name="N80 BASIC (1983)(Microsoft - NEC).d88" size="348848" crc="ff9416a4" sha1="3321c6a723545ef7f413a372683a1e40ef7ea4ef" offset="0" />
			</dataarea>
		</part>
	</software>

	<software name="n80basica" cloneof="n80basic">
		<description>N80 BASIC v1.8</description>
		<year>19??</year>
		<publisher>&lt;unknown&gt;</publisher>
		<part name="flop1" interface="pc8001_flop">
			<dataarea name="flop" size="348848">
				<rom name="N80 BASIC v1.8 (1981)(Microsoft).d88" size="348848" crc="00b2a439" sha1="ce234142ec31e8ec2e862042b2c6889650ed59d6" offset="0" />
			</dataarea>
		</part>
	</software>


<!-- These are going to be replaced by the correspondent separate tapes, as soon as possible!! -->

	<software name="pack1">
		<description>Dig Dug / Xevious / Nintendo no Golf / Nuts &amp; Milk</description>
		<year>19??</year>
		<publisher>&lt;unknown&gt;</publisher>
		<part name="flop1" interface="pc8001_flop">
			<dataarea name="flop" size="353200">
				<rom name="dig dug - xevious - nintendo no golf - nuts&amp;milk.d88" size="353200" crc="1e6c02fe" sha1="039c2e1831f8f4d0ca4ca2d9bc8ad857cf4bade2" offset="0" />
			</dataarea>
		</part>
	</software>

	<software name="pack2">
		<description>Dragon Slayer / Burger Time / Excite Bike / Dig Dug / Xevious</description>
		<year>19??</year>
		<publisher>&lt;unknown&gt;</publisher>
		<part name="flop1" interface="pc8001_flop">
			<dataarea name="flop" size="348848">
				<rom name="dragon slayer - burger time - excite bike - dig dug - xevious.d88" size="348848" crc="143636e6" sha1="077a419dac5c1562a04e6a8467cf8ecd7a590427" offset="0" />
			</dataarea>
		</part>
	</software>

	<software name="pack3">
		<description>Video-kun / F2 Grand Prix / Eggy</description>
		<year>19??</year>
		<publisher>&lt;unknown&gt;</publisher>
		<part name="flop1" interface="pc8001_flop">
			<dataarea name="flop" size="348848">
				<rom name="video-kun - f2 grand prix - eggy.d88" size="348848" crc="45d3515f" sha1="5d6def548da8f943eebdf7f524bea58ed1dab456" offset="0" />
			</dataarea>
		</part>
	</software>


</softwarelist>

=== jsmess/jsmess/hash/rainbow.xml
<?xml version="1.0"?>
<!DOCTYPE softwarelist SYSTEM "softwarelist.dtd">
<!-- Software from here: http://rainbow-100.com -->

<softwarelist name="rainbow" description="DEC Rainbow 100 Disk Images">
	<software name="concpm86">
		<description>Concurrent CP/M-86</description>
		<year>198?</year>
		<publisher>Digital Research</publisher>
		<part name="flop1" interface="floppy_5_25">
			<feature name="part_id" value="Boot Disk"/>
			<dataarea name="flop" size="309260">
				<rom name="ccpmsys.td0" size="309260" crc="4b175438" sha1="948ec04358d2adf05f2c077556e2bd899e87cbca" offset="0" />
			</dataarea>
		</part>
		<part name="flop2" interface="floppy_5_25">
			<feature name="part_id" value="Utilities Disk"/>
			<dataarea name="flop" size="322414">
				<rom name="ccpmutil.td0" size="322414" crc="f4b7332b" sha1="0e844b8c835370e2f8f095b0dc84dfdb7bc2135f" offset="0" />
			</dataarea>
		</part>
		<part name="flop3" interface="floppy_5_25">
			<feature name="part_id" value="Graphics Disk"/>
			<dataarea name="flop" size="193193">
				<rom name="ccpmgsx.td0" size="193193" crc="62c0668b" sha1="84ed7179defc3ee513c600cbd97078da2b529705" offset="0" />
			</dataarea>
		</part>
	</software>

	<software name="cpm8011">
		<description>CP/M-86/80 (Version 1.1)</description>
		<year>198?</year>
		<publisher>Digital Research</publisher>
		<part name="flop1" interface="floppy_5_25">
			<dataarea name="flop" size="204393">
				<rom name="cpmv11.td0" size="204393" crc="38f9ad05" sha1="ec39d974cdb757573ce026de84056dad08df3ce3a" offset="0" />
			</dataarea>
		</part>
	</software>

	<software name="cpm8021">
		<description>CP/M-86/80 (Version 2.1)</description>
		<year>198?</year>
		<publisher>Digital Research</publisher>
		<part name="flop1" interface="floppy_5_25">
			<dataarea name="flop" size="342476">
				<rom name="cpmv21.td0" size="342476" crc="efb74351" sha1="4ef27aff24793f0dfcdc38b1bb8238994d439eec" offset="0" />
			</dataarea>
		</part>
	</software>

	<software name="msdos201">
		<description>MS-DOS 2.01</description>
		<year>198?</year>
		<publisher>Microsoft</publisher>
		<part name="flop1" interface="floppy_5_25">
			<dataarea name="flop" size="208780">
				<rom name="msdos201.td0" size="208780" crc="7d652459" sha1="cb2f6f4a181032f69bdf339f2555dcfdfd1e7ef7" offset="0" />
			</dataarea>
		</part>
	</software>

	<software name="msdos211">
		<description>MS-DOS 2.11</description>
		<year>198?</year>
		<publisher>Microsoft</publisher>
		<part name="flop1" interface="floppy_5_25">
			<dataarea name="flop" size="409600">
				<rom name="msdos211.img" size="409600" crc="52f98712" sha1="83608857b38351fff99d65bb28b7cf8454668bbb" offset="0" />
			</dataarea>
		</part>
	</software>

	<software name="msdos31b">
		<description>MS-DOS 3.10b</description>
		<year>198?</year>
		<publisher>Microsoft</publisher>
		<part name="flop1" interface="floppy_5_25">
			<dataarea name="flop" size="338752">
				<rom name="msdos31b.td0" size="338752" crc="d12d5719" sha1="ec0c50ba812b45cc22503f2611e7abbcd8ba54f8" offset="0" />
			</dataarea>
		</part>
	</software>

	<software name="psystem">
		<description>p-System</description>
		<year>198?</year>
		<publisher>UCSD</publisher>
		<!-- Looking at the Disk image with a hex editor it says 1982 by SofTech Microsystems, Inc. will wait till emulation is of such state to enable it too boot before fixing this -->
		<!-- The Order of these needs to be sorted later-->
		<part name="flop1" interface="floppy_5_25">
			<dataarea name="flop" size="409600">
				<rom name="8086kit.img" size="409600" crc="64577e4f" sha1="ee4ba05bd8fbce8cac609589fc031cb5e0073564" offset="0" />
			</dataarea>
		</part>
		<part name="flop2" interface="floppy_5_25">
			<dataarea name="flop" size="409600">
				<rom name="fort_sys.img" size="409600" crc="d3ec79b2" sha1="96ac1bc6ffdb4067ec17b777ff1fb1dffcfbc958" offset="0" />
			</dataarea>
		</part>
		<part name="flop3" interface="floppy_5_25">
			<dataarea name="flop" size="409600">
				<rom name="pas_sys.img" size="409600" crc="302ecaf5" sha1="8e5b63ba1afde500c93431d96039811544a08ce3" offset="0" />
			</dataarea>
		</part>
		<part name="flop4" interface="floppy_5_25">
			<dataarea name="flop" size="409600">
				<rom name="pascal.img" size="409600" crc="42f485ad" sha1="f9ca68a56f598a1ad59ad8916635305a2cafa7bd" offset="0" />
			</dataarea>
		</part>
		<part name="flop5" interface="floppy_5_25">
			<dataarea name="flop" size="409600">
				<rom name="toolkit.img" size="409600" crc="a23b3aa0" sha1="07be31bec922697f337a5c2dfab1eb4125cf6e86" offset="0" />
			</dataarea>
		</part>
		<part name="flop6" interface="floppy_5_25">
			<dataarea name="flop" size="409600">
				<rom name="utils.img" size="409600" crc="45642488" sha1="912af05ed55b73a5b456d6e3166d9af576f3e60b" offset="0" />
			</dataarea>
		</part>
	</software>
</softwarelist>

=== jsmess/jsmess/hash/plus4_cart.xml
<?xml version="1.0"?>
<!DOCTYPE softwarelist SYSTEM "softwarelist.dtd">
<softwarelist name="plus4_cart" description="Commodore Plus/4 cartridges">
	
	<!-- Games -->
	
	<software name="atomicmi">
		<description>Atomic Mission</description>
		<year>1984</year>
		<publisher>Commodore</publisher>
		<info name="serial" value="T116005" />
		<part name="cart" interface="plus4_cart">
			<dataarea name="c1l" size="0x4000">
				<rom name="atomic-lo" size="0x2000" crc="8ee859ce" sha1="dac80035aa9c15c81d0ae7d80392d2be691dd55c" offset="0x0000" />
				<rom name="atomic-hi" size="0x2000" crc="f3ebd401" sha1="011b7fd7c7990c4189ac107f7da0f3df474007d1" offset="0x2000" />
			</dataarea>
		</part>
	</software>
	
	<software name="jackattk">
		<description>Jack Attack</description>
		<year>1984</year>
		<publisher>Commodore</publisher>
		<info name="serial" value="T116002" />
		<part name="cart" interface="plus4_cart">
			<dataarea name="c1l" size="0x4000">
				<rom name="jack-lo" size="0x2000" crc="c4201b23" sha1="dfba1151dc477d1096d5e4747fe07c104454d9ad" offset="0x0000" />
				<rom name="jack-hi" size="0x2000" crc="f67be343" sha1="c6ef59735d11a85538538c868dfc09c970070ab5" offset="0x2000" />
			</dataarea>
		</part>
	</software>
	
	<software name="piratead">
		<description>Pirate Adventure</description>
		<year>1984</year>
		<publisher>Commodore</publisher>
		<info name="serial" value="T116004" />
		<part name="cart" interface="plus4_cart">
			<dataarea name="c1l" size="0x4000">
				<rom name="pirate-lo" size="0x2000" crc="636ac403" sha1="45e3fa723bc58b1c2c0ff4ac428556629fc384bf" offset="0x0000" />
				<rom name="pirate-hi" size="0x2000" crc="d66c86e9" sha1="44d56f6fd32b5ba8202f674444a5bc4e7481ceb4" offset="0x2000" />
			</dataarea>
		</part>
	</software>
	
	<software name="strngeod">
		<description>Strange Odyssey</description>
		<year>1984</year>
		<publisher>Commodore</publisher>
		<info name="serial" value="T116006" />
		<part name="cart" interface="plus4_cart">
			<dataarea name="c1l" size="0x4000">
				<rom name="odyssey-lo" size="0x2000" crc="2a55241b" sha1="0fe437bae5b07a81aa8abf7496a685ba5bbf0e41" offset="0x0000" />
				<rom name="odyssey-hi" size="0x2000" crc="ca728068" sha1="78a087b731051b688ad572f80d0af15c01a44193" offset="0x2000" />
			</dataarea>
		</part>
	</software>

	<!-- Applications -->
	
	<software name="speedfrz" supported="no">
		<description>Speedy Freeze</description>
		<year>1988</year>
		<publisher>&lt;unknown&gt;</publisher>
		<part name="cart" interface="plus4_cart">
			<dataarea name="c1l" size="0x4000">
				<rom name="speedy.u1" size="0x2000" crc="74f180bc" sha1="79a4b19c50bc9a85c0356a3d2d7453b2d1d8266f" offset="0x0000" />
			</dataarea>
		</part>
	</software>

</softwarelist>

=== jsmess/jsmess/hash/ibmpcjr_flop.xml
<?xml version="1.0"?>
<!DOCTYPE softwarelist SYSTEM "softwarelist.dtd">
<!--  Needed to be dump:
	IBM PCjr club disk library (only an extracted collection exist)
-->
<softwarelist name="ibmpcjr_flop" description="IBM PCjr disk images">
	<software name="dos2">
		<description>IBM PC-DOS Version 2.00</description>
		<year>1983</year>
		<publisher>IBM</publisher>
		<part name="flop1" interface="floppy_5_25">
			<dataarea name="flop" size="368640">
				<rom name="dos2.ima" size="368640" crc="d0fb7d31" sha1="cbee7f6109fb0ed8a94de1893fc47ab066de36d3" offset="0x00000" />
			</dataarea>
		</part>
	</software>

	<software name="wordstar">
		<description>Wordstar for PCjr (Release 1.00)</description>
		<year>1987</year>
		<publisher>Micropro International</publisher>
		<part name="flop1" interface="floppy_5_25">
			<dataarea name="flop" size="368640">
				<rom name="disk 1.ima" size="368640" crc="81b95671" sha1="a5f33403b1e3762e6b1c2c84b279e093eec9501f" offset="0x00000" />
			</dataarea>
		</part>
		<part name="flop2" interface="floppy_5_25">
			<dataarea name="flop" size="368640">
				<rom name="disk 2.ima" size="368640" crc="d5c84856" sha1="ef138f490f302e687827b71b8d254143d870f895" offset="0x00000" />
			</dataarea>
		</part>
		<part name="flop3" interface="floppy_5_25">
			<dataarea name="flop" size="368640">
				<rom name="disk 3.ima" size="368640" crc="49884404" sha1="11c8c7d638ba00a1e42844a1efb09fd6f75ac7d4" offset="0x00000" />
			</dataarea>
		</part>
	</software>

	<software name="explore">
		<description>Exploring The IBM PCjr</description>
		<year>1983</year>
		<publisher>IBM Corp.</publisher>
		<part name="flop1" interface="floppy_5_25">
			<dataarea name="flop" size="163840">
				<rom name="exploring the ibm pcjr.ima" size="163840" crc="409ff73f" sha1="453ae5f3fa7781ece7d421dd973ce54204b9c99d" offset="0x00000" />
			</dataarea>
		</part>
	</software>

	<software name="sampler">
		<description>IBM PCjr Sampler</description>
		<year>198?</year>
		<publisher>IBM</publisher>
		<part name="flop1" interface="floppy_5_25">
			<dataarea name="flop" size="368640">
				<rom name="ibm pcjr sampler.ima" size="368640" crc="d0fb7d31" sha1="cbee7f6109fb0ed8a94de1893fc47ab066de36d3" offset="0x00000" />
			</dataarea>
		</part>
	</software>
</softwarelist>

=== jsmess/jsmess/mess/hash/pv1000.xml
<?xml version="1.0"?>
<!DOCTYPE softwarelist SYSTEM "softwarelist.dtd">

<!--

Undumped carts:

 * GPA-107 - Turpin ~ ターピン
 * GPA-108 - ??? [possibly no game used this ID]
 * GPA-110 - Fighting Bug ~ ファイティング バグ
 * GPA-111 - Space Panic ~ スペースパニック
 * GPA-112 - Naughty Boy ~ ノーティーボーイ
 * GPA-113 - ??? [possibly no game used this ID]

-->

<softwarelist name="pv1000" description="Casio PV-1000 cartridges">
	<!-- Serial: GPA-101 - Alt Title: プーヤン -->
	<software name="pooyan">
		<description>Pooyan</description>
		<year>1982</year>
		<publisher>Casio</publisher>
		<part name="cart" interface="pv1000_cart">
			<dataarea name="rom" size="8192">
				<rom name="pooyan.bin" size="8192" crc="bd6edc48" sha1="606b7d603da23e70012b361d7ffb53ea026f88f5" offset="0000" />
			</dataarea>
		</part>
	</software>

	<!-- Serial: GPA-102 - Alt Title: スーパーコブラ -->
	<software name="scobra">
		<description>Super Cobra</description>
		<year>1981</year>
		<publisher>Casio</publisher>
		<part name="cart" interface="pv1000_cart">
			<dataarea name="rom" size="8192">
				<rom name="scobra.bin" size="8192" crc="cdffc2cd" sha1="9e748050ccb0fa948b06346d241dfcd11868e8e2" offset="0000" />
			</dataarea>
		</part>
	</software>

	<!-- Serial: GPA-103 - Alt Title: ツターンカーム -->
	<software name="tutnkham">
		<description>Tutankham</description>
		<year>1982</year>
		<publisher>Casio</publisher>
		<part name="cart" interface="pv1000_cart">
			<dataarea name="rom" size="8192">
				<rom name="tutnkham.bin" size="8192" crc="a0b606d8" sha1="56efa2ab7c4a6db7b44714e46c5bf2ba71983ee8" offset="0000" />
			</dataarea>
		</part>
	</software>

	<!-- Serial: GPA-104 - Alt Title: アミダー -->
	<software name="amidar">
		<description>Amidar</description>
		<year>1982</year>
		<publisher>Casio</publisher>
		<part name="cart" interface="pv1000_cart">
			<dataarea name="rom" size="8192">
				<rom name="amidar.bin" size="8192" crc="c82628cc" sha1="00322d4025fef19728194442f9e06a4cccd01933" offset="0000" />
			</dataarea>
		</part>
	</software>

	<!-- Serial: GPA-105 - Alt Title: ディグダグ -->
	<software name="digdug" supported="no">
		<description>Dig Dug</description>
		<year>1982</year>
		<publisher>Casio</publisher>
		<part name="cart" interface="pv1000_cart">
			<dataarea name="rom" size="16384">
				<rom name="digdug.bin" size="16384" crc="a94f02fa" sha1="502a163c1ae88eccc7e9782261d86d4090cb41e1" offset="0000" />
			</dataarea>
		</part>
	</software>

	<!-- Serial: GPA-106 - Alt Title: ワープ＆ワープ -->
	<software name="warpwarp">
		<description>Warp &amp; Warp</description>
		<year>1981</year>
		<publisher>Casio</publisher>
		<part name="cart" interface="pv1000_cart">
			<dataarea name="rom" size="8192">
				<rom name="warpwarp.bin" size="8192" crc="2a0d4ad9" sha1="f9ffca3a1d85b116dd92f118f9ea940bf2449db5" offset="0000" />
			</dataarea>
		</part>
	</software>

	<!-- Serial: GPA-109 - Alt Title: パチンコＵＦＯ -->
	<software name="pchnkufo" supported="no">
		<description>Pachinko-UFO</description>
		<year>1982</year>
		<publisher>Casio</publisher>
		<part name="cart" interface="pv1000_cart">
			<dataarea name="rom" size="16384">
				<rom name="pchnkufo.bin" size="16384" crc="9ee981ab" sha1="d6ca45430a34ce0090ba882ade5a2268a862d4f4" offset="0000" />
			</dataarea>
		</part>
	</software>

	<!-- Serial: GPA-114 - Alt Title: ダーティー カメレオン -->
	<software name="dirtychm">
		<description>Dirty Chameleon</description>
		<year>198?</year>
		<publisher>Casio</publisher>
		<part name="cart" interface="pv1000_cart">
			<dataarea name="rom" size="8192">
				<rom name="dirtychm.bin" size="8192" crc="8e7fb358" sha1="63e94cc01410aefd59b465105e701330dc13c398" offset="0000" />
			</dataarea>
		</part>
	</software>

	<!-- Serial: GPA-115 - Alt Title: エキサイト麻雀 -->
	<software name="excitemj">
		<description>Excite Mahjong</description>
		<year>1982</year>
		<publisher>Casio</publisher>
		<part name="cart" interface="pv1000_cart">
			<dataarea name="rom" size="16384">
				<rom name="excitemj.bin" size="16384" crc="0d2f829c" sha1="6cc9e5d234bc1b483108ae4dc79d644802a64ef0" offset="0000" />
			</dataarea>
		</part>
	</software>

</softwarelist>

=== jsmess/jsmess/hash/trs80m2.xml
<?xml version="1.0"?>
<!DOCTYPE softwarelist SYSTEM "softwarelist.dtd">
<softwarelist name="trs80m2" description="Tandy TRS-80 Model II disk images">
	<software name="cpm22">
		<!-- Requires 64K RAM -->
		<description>CP/M 2.2</description>
		<year>1983</year>
		<publisher>Pickles &amp; Trout</publisher>
		<part name="flop" interface="floppy_8">
			<dataarea name="flop" size="318931">
				<rom name="cpm22.imd" size="318931" crc="10bce6d2" sha1="8912ef448725774d8a10bfa484342a8dfa81a824" offset="0" />
			</dataarea>
		</part>
	</software>

	<software name="tdos20">
		<description>TRSDOS v2.0a</description>
		<year>1980</year>
		<publisher>Tandy</publisher>
		<info name="catalog" value="26-4910" />
		<part name="flop1" interface="floppy_8">
			<dataarea name="flop" size="146181">
				<rom name="tdos20a.imd" size="146181" crc="b6d2fa9a" sha1="a93accf032b19cdd0122ccf45ba0af90d44f0f84" offset="0" />
			</dataarea>
		</part>
		<part name="flop2" interface="floppy_8">
			<dataarea name="flop" size="146079">
				<rom name="tdos20b.imd" size="146079" crc="decce25d" sha1="97f06369d66abbd5d46cdc6f5e22c32e04a9d686" offset="0" />
			</dataarea>
		</part>
		<part name="flop3" interface="floppy_8">
			<dataarea name="flop" size="131043">
				<rom name="tdoscalc.imd" size="131043" crc="78c1666e" sha1="72e438da397aac4da099c76860426247440f07fd" offset="0" />
			</dataarea>
		</part>
	</software>

	<software name="profile2">
		<description>PROFILE II</description>
		<year>1980</year>
		<publisher>Tandy</publisher>
		<info name="catalog" value="26-4512" />
		<part name="flop" interface="floppy_8">
			<dataarea name="flop" size="215804">
				<rom name="profile2.imd" size="215804" crc="8997532d" sha1="b0b7c738f5e23b7631741475bec25df2451c2a63" offset="0" />
			</dataarea>
		</part>
	</software>

	<software name="script">
		<description>SCRIPTSIT 2.0</description>
		<year>1981</year>
		<publisher>Tandy</publisher>
		<info name="catalog" value="26-4531" />
		<part name="flop" interface="floppy_8">
			<dataarea name="flop" size="227787">
				<rom name="script.imd" size="227787" crc="1cec0e85" sha1="73bfa56e2382ca04fd42f5b108699a1d9904dba2" offset="0" />
			</dataarea>
		</part>
	</software>
</softwarelist>
